const CYPRESS_VERSION = '3.5.0';
const CYPRESS_WEBPACK_PREPROCESSOR_VERSION = '4.1.0';
const CYPRESS_FILE_UPLOAD_VERSION = '3.1.4';

module.exports = {
    CYPRESS_VERSION,
    CYPRESS_FILE_UPLOAD_VERSION,
    CYPRESS_WEBPACK_PREPROCESSOR_VERSION
};
